### ISSUE TITLE
Need option to propagate some headers 'as-is' in interceptors/handlers

### ISSUE THREAD

**Issue by eoliphan** [steffan-westcott/clj-otel#12]
Hi, first great lib, really takes a lot of the pain out of using otel w/ clojure.  

Anyway, I'm using Clj-Otel on AWS w/ datomic ions.  So http requests are basically:

`APIGW (w/ xray) -> AWS Lambda (w/ xray) -> Datomic Cloud JVM (instrumented w/ otel) -> Datomic Ion adapter (puts ring headers on request) -> my handler func w/ pedestal router (clj-otel integrated)`

I'm having a problem with trace propagation, as in this config, APIGW is going to stick an XRay **X-Amzn-Trace-Id** header on the request, that gets carried along to the handler.   But traces stop at the lambda, and this appears to be due to the fact that the span doesn't have the **X-Amzn-Trace-Id** attribute, therefore the Xray propagator isn't property linking stuff up.  

The `:captured-request-headers` option for the `(server-span-interceptors)` function works great for generically adding additional headers as attributes with that **http.request.header** prefix.  But need to be able to specify similar except that the specified headers are added as attributes 'as-is'.   Or perhaps just an option for a generic function that could be used to further tweak the final map of attributes that end up on that `:io.opentelemetry/server-request-attrs` pedestal context attribute

**Comment by steffan-westcott** [comment]
What you are describing utilises a fundamental concept called [context propagation](https://cljdoc.org/d/com.github.steffan-westcott/clj-otel-api/0.2.4.1/doc/concepts#_context_propagation) in OpenTelemetry terms. By default, both OpenTelemetry Java and `clj-otel` have enabled propagators for W3C Trace Context and W3C baggage header, though other propagators are available. There is an [AWS X-Ray Trace Header protocol propagator](https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/aws-xray-propagator), but it is not included nor enabled by default.

The method to include and enable the AWS X-Ray Trace Header protocol propagator depends on how your application is run.

- If the application is [run with the instrumentation agent](https://cljdoc.org/d/com.github.steffan-westcott/clj-otel-api/0.2.4.1/doc/guides#_run_with_the_opentelemetry_instrumentation_agent), ensure the system property `otel.propagators` [comma delimited list of propagators](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure#propagator) includes `xray`
- If the application is [run with the autoconfigure SDK extension](https://cljdoc.org/d/com.github.steffan-westcott/clj-otel-api/0.2.4.1/doc/guides#_run_with_autoconfigure_sdk_extension), set the `otel.propagators` system property as above and include the Java library dependency `io.opentelemetry.contrib/opentelemetry-aws-xray-propagator`
- If the application is [run with a programmatically configured SDK](https://cljdoc.org/d/com.github.steffan-westcott/clj-otel-api/0.2.4.1/doc/guides#_run_with_programmatically_configured_sdk), include the Clojure dependency `com.github.steffan-westcott/clj-otel-contrib-aws-xray-propagator` and ensure `propagators` option to [`init-otel-sdk!`](https://cljdoc.org/d/com.github.steffan-westcott/clj-otel-sdk/0.2.4.1/api/steffan-westcott.clj-otel.sdk.otel-sdk#init-otel-sdk!) includes [`(steffan-westcott.clj-otel.propagator.aws-xray/aws-xray-propagator)`](https://cljdoc.org/d/com.github.steffan-westcott/clj-otel-contrib-aws-xray-propagator/0.2.4.1/api/steffan-westcott.clj-otel.propagator.aws-xray)

The `captured-request-headers` option is unrelated to your use case. That option controls which HTTP headers are copied as attributes into the server span. It has no bearing on context propagation at all.

**Comment by eoliphan** [comment]
Ok, understand.   So, i'm actually using AWS' implementation of both the agent and the collector.  Per their agent docs, it seems like xray should already be in the list.  _"Out of the box, it propagates traces using all of W3C Trace Context, B3, and X-Amzn-Trace-Id."_. But going to double check.   If it is enabled, one problem might be that this 'http request' is actually coming in via this datomic/lambda adapter.  So wondering if agent doesn't 'know' about the code in this case that needs to be instrumented.

**Comment by steffan-westcott** [comment]
I have no experience with this myself, but I know that support for OpenTelemetry with AWS Lambda is typically implemented using a Lambda Layer. There is an official AWS ADOT for this : https://aws-otel.github.io/docs/getting-started/lambda
