### ISSUE TITLE
Request: Handle `captured-request-headers` passed to `wrap-server-span` even when `create-span?` is false

### ISSUE THREAD

**Issue by devurandom** [steffan-westcott/clj-otel#17]
Currently `steffan-westcott.clj-otel.api.trace.http/wrap-server-span` only uses `captured-request-headers` when `create-span?` is passed:
```clj
   (cond-> handler
     :always            (wrap-bound-context)
     create-span?       (wrap-new-server-span create-span-opts)
     create-span?       (wrap-server-request-attrs create-span-opts)
     (not create-span?) (wrap-existing-server-span))
```

It would be nice if `wrap-server-span` / `steffan-westcott.clj-otel.api.trace.http/wrap-server-request-attrs` would capture the request headers either way. Maybe through some variant of `steffan-westcott.clj-otel.api.trace.http/server-request-attrs` that does not set all attributes, but do only this last part of it:
```clj
(cond-> ,,,
      captured-request-headers
      (merge-headers-attrs "http.request.header." captured-request-headers headers))
```

The alternative is setting the system property `otel.instrumentation.http.server.capture-request-headers` or environment variable `OTEL_INSTRUMENTATION_HTTP_SERVER_CAPTURE_REQUEST_HEADERS` that the OpenTelemetry Java Agent understands: https://opentelemetry.io/docs/languages/java/automatic/configuration/#capturing-http-request-and-response-headers

**Comment by steffan-westcott** [comment]
When using the middleware `wrap-server-span`, the appropriate setting for `create-span?` is dictated by the presence of the OpenTelemetry instrumentation agent:
- If the application is run with the agent, `create-span?` should be set to false
- If the application is run without the agent, `create-span?` should be set to true

When using the agent, it should be configured as described in the [documentation](https://opentelemetry.io/docs/languages/java/automatic/configuration/). The operation and configuration of the agent is outside the scope of `clj-otel`, as it is not part of the OpenTelemetry API. The agent is responsible for creating server spans for supported HTTP servers. As you have noted, part of the agent configuration specifies which request headers are captured as attributes on the server span. When using the agent, it creates the server span with the desired header attributes, `clj-otel` has no control over this.

In your scenario, `create-span?` is false and (for correct operation) the application is run with the agent. The agent will create server spans, and the agent configuration specifies which headers are added. `clj-otel` has no influence on agent operation.
