### ISSUE TITLE
Function to set sync gauges?

### ISSUE THREAD

**Issue by leahneukirchen** [steffan-westcott/clj-otel#20]
Good to see support for synchronous Gauges, but I wonder if there should be an `instrument/set!` to set them? I guess one can work around by calling `.set` directly, but this is not very idiomatic.

**Comment by steffan-westcott** [comment]
@leahneukirchen Thank you for highlighting this omission. I've verified the new `steffan-westcott.clj-otel.api.metrics.instrument/set!` function works as intended. Thanks again!
